#!/bin/bash
### BEGIN INIT INFO
# Provides:          garbd
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop the garbd daemon
# Description:       Start/Stop the garbd daemon.
### END INIT INFO

# Copyright (C) 2012 Codership <info@codership.com>
#
# init.d script for garbd
#

# Source function library.
. /lib/lsb/init-functions
config=/etc/mysql/garb.conf


log_failure() {

		log_failure_msg "$*"
}

PIDFILE=/var/run/garbd

prog=$(which garbd)

program_start() {
	local rcode

	log_daemon_msg "Starting $prog:"
	
	$prog $OPTIONS
		
	rcode=$?
	# Hack: sleep a bit to give garbd some time to fork
	sleep 1
	[ $rcode -eq 0 ] && pidof $prog > $PIDFILE
	log_end_msg $rcode

	return $rcode
}

program_stop() {
	local rcode
	
	start-stop-daemon --stop --quiet --oknodo --retry TERM/30/KILL/5 --pidfile $PIDFILE
	rcode=$?
	log_end_msg $rcode
	
	[ $rcode -eq 0 ] && rm -f $PIDFILE
	return $rcode
}

program_status() {

		status_of_proc -p $PIDFILE "$prog" garb
}

start() {

	if [ -r $PIDFILE ]; then
		log_failure "$prog is already running with PID $(cat ${PIDFILE})"
		return 0
	fi

	OPTIONS="--cfg $config --daemon"

	program_start $OPTIONS
}

stop() {
	program_stop
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	program_status
	;;
  restart)
	stop
	start
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	exit 2
esac

exit $?

